services:
  linkstack:
    image: linkstackorg/linkstack
    container_name: linkstack
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      - HTTP_SERVER_NAME="www.example.xyz"
      - HTTPS_SERVER_NAME="www.example.xyz"
      - SERVER_ADMIN="admin@example.xyz"
      - TZ="America/Chicago"
      - PHP_MEMORY_LIMIT="512M"
      - UPLOAD_MAX_FILESIZE="8M"
    volumes:
      - linkstack_data:/htdocs

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --schedule "0 0 4 * * *" --cleanup
    restart: unless-stopped

volumes:
  linkstack_data:
