services:
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    user: 1000:1000 
    ports:
      - "4533:4533"
    restart: unless-stopped
    environment:
      ND_SCANINTERVAL: 1h
      ND_SESSIONTIMEOUT: 24h
      ND_LOGLEVEL: info
    volumes:
      - "/var/lib/docker/volumes/navidrome_data:/data"
      - "/music:/music:ro"
