services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment:
      HOMEPAGE_ALLOWED_HOSTS: gethomepage.dev # add your domains and ips here (comma separated value). see gethomepage.dev/installation/#homepage_allowed_hosts for more info
      PUID: 1000 # optional, your user id
      PGID: 1000 # optional, your group id
    ports:
      - 3000:3000
    volumes:
      - /home/username/docker/homepage/config:/app/config # path to your config folder (nested in the same folder as the docker-compose.yml file)
      - /var/run/docker.sock:/var/run/docker.sock:ro # optional, for docker integrations
    restart: unless-stopped
