version: '3.8'

volumes:
  dbdata:
  appmedia:

services:
  db:
    image: webodm/webodm_db
    container_name: webodm_db
    expose:
      - "5432"
    volumes:
      - ${WO_DB_DIR:-dbdata}:/var/lib/postgresql/data:Z
    restart: unless-stopped
    oom_score_adj: -100

  webapp:
    image: webodm/webodm_webapp
    container_name: webodm_webapp
    entrypoint: /bin/bash -c "service cron start && chmod +x /webodm/*.sh && /bin/bash -c \"/webodm/wait-for-postgres.sh db /webodm/wait-for-it.sh -t 0 broker:6379 -- /webodm/start.sh\""
    volumes:
      - ${WO_MEDIA_DIR:-appmedia}:/webodm/app/media:z
    ports:
      - "${WO_PORT:-8000}:8000"
    depends_on:
      - db
      - broker
      - worker
      - node-odx-1
    environment:
      - WO_PORT=${WO_PORT:-8000}
      - WO_HOST=${WO_HOST:-localhost}
      - WO_DEBUG=${WO_DEBUG:-False}
      - WO_BROKER=redis://broker:6379/0
      - WO_SECRET_KEY=${WO_SECRET_KEY:-}
      - WEB_CONCURRENCY=${WEB_CONCURRENCY:-}
      - WO_DEFAULT_NODES=${WO_DEFAULT_NODES:-1}
    restart: unless-stopped
    oom_score_adj: 0

  broker:
    image: redis:7.0.10
    container_name: webodm_broker
    restart: unless-stopped
    oom_score_adj: -500

  worker:
    image: webodm/webodm_webapp
    container_name: webodm_worker
    entrypoint: /bin/bash -c "/webodm/wait-for-postgres.sh db /webodm/wait-for-it.sh -t 0 broker:6379 -- /webodm/wait-for-it.sh -t 0 webapp:8000 -- /webodm/worker.sh start"
    volumes:
      - ${WO_MEDIA_DIR:-appmedia}:/webodm/app/media:z
    depends_on:
      - db
      - broker
    environment:
      - WO_BROKER=redis://broker:6379/0
      - WO_DEBUG=${WO_DEBUG:-False}
      - WO_SECRET_KEY=${WO_SECRET_KEY:-}
      - WEB_CONCURRENCY=${WEB_CONCURRENCY:-}
    restart: unless-stopped
    oom_score_adj: 250

  node-odx-1:
    image: webodm/nodeodx
    container_name: webodm_nodeodx
    expose:
      - "3000"
    restart: unless-stopped
    oom_score_adj: 500
